#include "PS1LuaScriptLanguage.hpp"
#include "PS1LuaScript.hpp"

#include "ApiData.gen.hpp"

#include <godot_cpp/classes/code_edit.hpp>
#include <godot_cpp/core/error_macros.hpp>
#include <godot_cpp/variant/array.hpp>
#include <godot_cpp/variant/color.hpp>
#include <godot_cpp/variant/dictionary.hpp>
#include <godot_cpp/variant/typed_array.hpp>

using namespace godot;

String PS1LuaScriptLanguage::_get_name() const {
	return "PS1Lua";
}

String PS1LuaScriptLanguage::_get_type() const {
	return "PS1LuaScript";
}

String PS1LuaScriptLanguage::_get_extension() const {
	return "lua";
}

PackedStringArray PS1LuaScriptLanguage::_get_recognized_extensions() const {
	PackedStringArray a;
	a.push_back("lua");
	return a;
}

PackedStringArray PS1LuaScriptLanguage::_get_reserved_words() const {
	static const char *kw[] = {
		"and", "break", "do", "else", "elseif", "end", "false", "for",
		"function", "goto", "if", "in", "local", "nil", "not", "or",
		"repeat", "return", "then", "true", "until", "while", "self"
	};
	PackedStringArray a;
	for (const char *k : kw) {
		a.push_back(k);
	}
	return a;
}

PackedStringArray PS1LuaScriptLanguage::_get_comment_delimiters() const {
	PackedStringArray a;
	a.push_back("--");
	return a;
}

PackedStringArray PS1LuaScriptLanguage::_get_doc_comment_delimiters() const {
	PackedStringArray a;
	a.push_back("---");
	return a;
}

PackedStringArray PS1LuaScriptLanguage::_get_string_delimiters() const {
	PackedStringArray a;
	a.push_back("\" \"");
	a.push_back("' '");
	return a;
}

bool PS1LuaScriptLanguage::_supports_builtin_mode() const { return false; }
bool PS1LuaScriptLanguage::_supports_documentation() const { return false; }
bool PS1LuaScriptLanguage::_can_inherit_from_file() const { return false; }
bool PS1LuaScriptLanguage::_is_using_templates() { return true; }

Ref<Script> PS1LuaScriptLanguage::_make_template(const String &p_template, const String &p_class_name, const String &p_base_class_name) const {
	Ref<PS1LuaScript> s;
	s.instantiate();
	String src = String("-- ") + p_class_name + ".lua\n"
			"-- Attached to a PS1Godot node. See psxsplash-main/src/luaapi.hh\n"
			"-- for the full API reference.\n"
			"\n"
			"function onEnable(self)\n"
			"end\n"
			"\n"
			"function onUpdate(self, dt)\n"
			"end\n";
	s->_set_source_code(src);
	return s;
}

Dictionary PS1LuaScriptLanguage::_validate(const String &p_script, const String &p_path, bool p_validate_functions, bool p_validate_errors, bool p_validate_warnings, bool p_validate_safe_lines) const {
	Dictionary d;
	d["valid"] = true;
	d["errors"] = Array();
	d["warnings"] = Array();
	d["functions"] = Array();
	d["safe_lines"] = Array();
	d["class_name"] = String();
	d["class_icon_path"] = String();
	d["class_base_type"] = String();
	d["class_member_lines"] = Array();
	return d;
}

TypedArray<Dictionary> PS1LuaScriptLanguage::_get_public_functions() const { return TypedArray<Dictionary>(); }
Dictionary PS1LuaScriptLanguage::_get_public_constants() const { return Dictionary(); }
TypedArray<Dictionary> PS1LuaScriptLanguage::_get_public_annotations() const { return TypedArray<Dictionary>(); }

TypedArray<Dictionary> PS1LuaScriptLanguage::_get_built_in_templates(const StringName &p_object) const {
	Dictionary t;
	t["inherit"] = "Node";
	t["name"] = "Empty";
	t["description"] = "Empty PS1 Lua behavior script.";
	t["content"] = String(
			"-- _CLASS_NAME_.lua\n"
			"function onEnable(self)\n"
			"end\n"
			"\n"
			"function onUpdate(self, dt)\n"
			"end\n");
	t["id"] = 0;
	t["origin"] = 0;

	TypedArray<Dictionary> arr;
	arr.push_back(t);
	return arr;
}

bool PS1LuaScriptLanguage::_handles_global_class_type(const String &p_type) const { return false; }
Dictionary PS1LuaScriptLanguage::_get_global_class_name(const String &p_path) const { return Dictionary(); }

// ─── Autocomplete ───────────────────────────────────────────────────────
//
// Data source: ps1lua::API_ENTRIES, generated by gen_api_data.py from
// psxsplash-main/src/luaapi.hh at build time (see SConstruct).
//
// Trigger contexts we handle:
//   1. `Entity.<prefix>`         → methods in Entity namespace matching prefix
//   2. `<prefix>` at identifier start → all namespaces matching prefix
//   3. `Method(<partial>)` open paren → `call_hint` with the signature
//
// Everything more ambitious (type flow, local-variable inference,
// cross-file completion) is deferred to a later phase; this covers
// 80% of the pain from just typing `Ent` and blanking on method names.

static bool is_ident_char(char32_t c) {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
	       (c >= '0' && c <= '9') || c == '_';
}

// Scan backward from end of `code` to find the current token being
// typed. Returns the token's start position (into `code`) in out_start.
// A "token" here is a maximal run of identifier chars, optionally
// preceded by a single `.` + another identifier (the namespace).
struct CompletionContext {
	int token_start;  // start of the prefix being matched
	int dot_pos;      // -1 if no namespace; otherwise position of the `.`
	String ns;        // empty if no namespace
	String prefix;    // the partial identifier the author is typing
	bool in_call;     // true if cursor sits inside an open `(` — show hint
	String call_ns;   // namespace of the surrounding call (if in_call)
	String call_name; // method name of the surrounding call (if in_call)
};

static CompletionContext scan_context(const String &code) {
	CompletionContext ctx;
	ctx.token_start = code.length();
	ctx.dot_pos = -1;
	ctx.in_call = false;

	// Godot embeds U+FFFF as a cursor sentinel in the string passed to
	// _complete_code — the char shows up as `￿` in console output.
	// Find it so we scan BACKWARD from the real cursor position rather
	// than from end-of-file. If absent, treat end-of-file as cursor.
	int cursor = -1;
	int clen = code.length();
	for (int k = 0; k < clen; k++) {
		if ((char32_t)code[k] == 0xFFFF) { cursor = k; break; }
	}
	if (cursor < 0) cursor = clen;

	int i = cursor - 1;

	// Walk back over identifier chars to find the current prefix.
	while (i >= 0 && is_ident_char(code[i])) i--;
	int prefix_start = i + 1;
	ctx.prefix = code.substr(prefix_start, cursor - prefix_start);
	ctx.token_start = prefix_start;

	// Optional `.<namespace>` preceding the prefix.
	if (i >= 0 && (char32_t)code[i] == '.') {
		ctx.dot_pos = i;
		int ns_end = i;
		i--;
		while (i >= 0 && is_ident_char(code[i])) i--;
		int ns_start = i + 1;
		if (ns_start < ns_end) {
			ctx.ns = code.substr(ns_start, ns_end - ns_start);
		}
	}

	// Call-hint detection: if not already in `ns.prefix` form, look for
	// an unbalanced `(` somewhere above — if we find one preceded by a
	// `ns.name`, populate call_ns / call_name.
	if (ctx.ns.is_empty() && !ctx.in_call) {
		int depth = 0;
		int j = cursor - 1;
		while (j >= 0) {
			char32_t c = code[j];
			if (c == ')') depth++;
			else if (c == '(') {
				if (depth == 0) {
					// Matched — the `(` at position j is the open paren
					// surrounding the cursor. Look backward from j-1 for
					// an identifier and optional namespace.
					int k = j - 1;
					while (k >= 0 && is_ident_char(code[k])) k--;
					int name_start = k + 1;
					int name_end = j;
					if (name_start < name_end &&
						k >= 0 && (char32_t)code[k] == '.') {
						int dot = k;
						k--;
						while (k >= 0 && is_ident_char(code[k])) k--;
						int ns_start = k + 1;
						int ns_end = dot;
						if (ns_start < ns_end) {
							ctx.in_call = true;
							ctx.call_ns = code.substr(ns_start, ns_end - ns_start);
							ctx.call_name = code.substr(name_start, name_end - name_start);
						}
					}
					break;
				}
				depth--;
			}
			else if (c == '"' || c == '\'') {
				// Skip string literal. Walk back past the matching quote.
				char32_t quote = c;
				j--;
				while (j >= 0 && (char32_t)code[j] != quote) {
					if (j > 0 && (char32_t)code[j - 1] == '\\') j--;
					j--;
				}
			}
			j--;
		}
	}
	return ctx;
}

static bool starts_with_ci(const String &s, const String &prefix) {
	// Case-sensitive match — Lua identifiers are case-sensitive, and
	// the PS1Godot API is PascalCased deliberately so authors can
	// distinguish `Camera` (runtime) from a hypothetical local `camera`.
	if (prefix.length() > s.length()) return false;
	return s.substr(0, prefix.length()) == prefix;
}

// Build a call-hint string like "Camera.Shake(intensity, frames) -> void".
static String format_hint(const ps1lua::ApiEntry &e) {
	String s = String(e.ns) + "." + String(e.name) + "(" + String(e.args) + ")";
	if (e.ret[0] != 0) {
		s += String(" -> ") + String(e.ret);
	}
	return s;
}

// Godot option dict keys (matching CodeEdit::add_code_completion_option):
// "kind" = CodeEdit::CodeCompletionKind
// "display" = what shows in the popup
// "insert_text" = what gets inserted when picked
// "font_color" = REQUIRED — Godot 4.7 logs "!op.has(font_color)" errors
//                for every option missing it
// "icon" = optional Resource ref
// "default_value" = optional Variant
// "location" = defaults to 1024 (LOCATION_OTHER) — treated as "builtin"
//
// Doc fields tried (different Godot versions honor different keys, so we
// stuff the same string into all three; harmless overhead per option):
//   "description" — what GDScript's own completion uses
//   "tooltip"     — fallback for some 4.x branches
//   "doc_brief"   — the EditorHelp short-summary key
//
// As a last-resort fallback we also embed a single-line truncation of the
// doc right into the `display` field, so even editors that ignore every
// description key still show *something* when the author hovers in the
// popup.
static Dictionary make_option(int kind, const String &display, const String &insert_text, const String &doc = String()) {
	Dictionary d;
	d["kind"] = kind;
	if (!doc.is_empty()) {
		// Pad the display with a brief tail. Truncate to keep the
		// popup line readable; full doc still travels via the
		// description/tooltip keys below.
		String brief = doc;
		int nl = brief.find("\n");
		if (nl >= 0) brief = brief.substr(0, nl);
		const int kBriefMax = 64;
		if (brief.length() > kBriefMax) {
			brief = brief.substr(0, kBriefMax - 1) + String::utf8("…");
		}
		d["display"] = display + String::utf8("  —  ") + brief;
	} else {
		d["display"] = display;
	}
	d["insert_text"] = insert_text;
	d["font_color"] = Color(1, 1, 1, 1);
	d["icon"] = Variant();
	d["default_value"] = Variant();
	d["location"] = 1024;
	if (!doc.is_empty()) {
		d["description"] = doc;
		d["tooltip"]     = doc;
		d["doc_brief"]   = doc;
	}
	return d;
}

Dictionary PS1LuaScriptLanguage::_complete_code(const String &p_code, const String &p_path, Object *p_owner) const {
	Dictionary result;
	result["result"] = OK;
	result["force"] = false;
	result["call_hint"] = String();
	TypedArray<Dictionary> options;

	CompletionContext ctx = scan_context(p_code);

	// 1. Member access `<ns>.<prefix>` — list methods in that namespace.
	if (!ctx.ns.is_empty()) {
		for (int i = 0; i < ps1lua::API_ENTRY_COUNT; i++) {
			const ps1lua::ApiEntry &e = ps1lua::API_ENTRIES[i];
			if (ctx.ns != String(e.ns)) continue;
			String name = String(e.name);
			if (!ctx.prefix.is_empty() && !starts_with_ci(name, ctx.prefix)) continue;
			// Display shows the full sig; insert_text is just the method
			// name so the author can keep typing args afterward.
			String display = String(e.name) + "(" + String(e.args) + ")";
			String doc = String(e.doc);
			if (!String(e.ret).is_empty()) {
				// Prepend the return-type phrase so authors see
				// "→ object or nil — Finds first object with matching name"
				// at a glance, even when there's no description text.
				String ret_prefix = String::utf8("→ ") + String(e.ret);
				doc = doc.is_empty() ? ret_prefix : (ret_prefix + " · " + doc);
			}
			options.push_back(make_option(
				(int)CodeEdit::KIND_FUNCTION, display, name, doc));
		}
		result["options"] = options;
		return result;
	}

	// 2. Bare prefix — suggest unique namespaces matching prefix.
	if (!ctx.prefix.is_empty()) {
		PackedStringArray seen;
		for (int i = 0; i < ps1lua::API_ENTRY_COUNT; i++) {
			String ns = String(ps1lua::API_ENTRIES[i].ns);
			if (seen.has(ns)) continue;
			seen.push_back(ns);
			if (!starts_with_ci(ns, ctx.prefix)) continue;
			// Build a quick "namespace doc" by counting members.
			int member_count = 0;
			for (int j = 0; j < ps1lua::API_ENTRY_COUNT; j++) {
				if (ns == String(ps1lua::API_ENTRIES[j].ns)) member_count++;
			}
			String ns_doc = vformat("PS1Godot Lua namespace · %d method(s)", member_count);
			options.push_back(make_option(
				(int)CodeEdit::KIND_CLASS, ns, ns, ns_doc));
		}
	}

	// 3. Call hint if cursor is inside an open paren of a known method.
	if (ctx.in_call) {
		for (int i = 0; i < ps1lua::API_ENTRY_COUNT; i++) {
			const ps1lua::ApiEntry &e = ps1lua::API_ENTRIES[i];
			if (ctx.call_ns == String(e.ns) && ctx.call_name == String(e.name)) {
				result["call_hint"] = format_hint(e);
				break;
			}
		}
	}

	result["options"] = options;
	return result;
}

// ── _lookup_code — hover tooltip + Ctrl-Click navigation ────────────
//
// `p_symbol` arrives in either of two shapes depending on what the
// editor parsed under the cursor:
//   - "Audio.PlaySfx"     (namespace.method)
//   - "Audio"             (bare namespace)
// We walk API_ENTRIES looking for a match and build a descriptor dict
// the editor renders as a tooltip / docs panel.
//
// Result dict keys mirror Godot's internal LookupResult struct:
//   "result"        Error::OK if found, ERR_UNAVAILABLE otherwise.
//   "type"          LookupResult enum: 1 = CLASS, 4 = CLASS_METHOD.
//   "class_name"    The PS1Godot Lua namespace ("Audio").
//   "class_member"  The method name ("PlaySfx") for method lookups.
//   "description"   Full doc text — newer Godot branches render this.
//   "tooltip"       Same content under a different key (some 4.x render
//                   paths look here instead).
//   "doc"           Catch-all for older / forked Godot builds.
// Stuffing the doc into three fields is a few bytes wasted; the
// editor picks one and ignores the rest.
Dictionary PS1LuaScriptLanguage::_lookup_code(const String &p_code,
                                              const String &p_symbol,
                                              const String &p_path,
                                              Object *p_owner) const {
	Dictionary d;
	d["result"] = ERR_UNAVAILABLE;
	d["type"] = 0;   // LOOKUP_RESULT_SCRIPT_LOCATION — safe default the
	                 // editor treats as "found nothing" alongside the
	                 // error result.

	if (p_symbol.is_empty()) return d;

	// Split "ns.method" → (ns, method). Bare namespace is also valid
	// — we look that up as a CLASS-kind result.
	int dot = p_symbol.find(".");
	String ns   = (dot >= 0) ? p_symbol.substr(0, dot)        : p_symbol;
	String mem  = (dot >= 0) ? p_symbol.substr(dot + 1)       : String();

	if (mem.is_empty()) {
		// Bare namespace — check that ns appears in the API at all.
		bool found_ns = false;
		int member_count = 0;
		for (int i = 0; i < ps1lua::API_ENTRY_COUNT; i++) {
			if (ns == String(ps1lua::API_ENTRIES[i].ns)) {
				found_ns = true;
				member_count++;
			}
		}
		if (!found_ns) return d;

		String desc = vformat(
			"PS1Godot Lua API namespace · %d method(s)\n"
			"Type `%s.` to see members.",
			member_count, ns);
		d["result"]       = OK;
		d["type"]         = 1;   // LOOKUP_RESULT_CLASS
		d["class_name"]   = ns;
		d["description"]  = desc;
		d["tooltip"]      = desc;
		d["doc"]          = desc;
		return d;
	}

	// Namespace.method — look up the exact entry.
	for (int i = 0; i < ps1lua::API_ENTRY_COUNT; i++) {
		const ps1lua::ApiEntry &e = ps1lua::API_ENTRIES[i];
		if (ns != String(e.ns) || mem != String(e.name)) continue;

		// Build a humanly-readable tooltip:
		//   Audio.PlaySfx(name [, vol]) → boolean
		//
		//   Plays a one-shot SFX clip by name. Returns false if the
		//   clip wasn't found.
		String sig = String(e.ns) + "." + String(e.name) +
		             "(" + String(e.args) + ")";
		if (!String(e.ret).is_empty()) {
			sig += String::utf8(" → ") + String(e.ret);
		}
		String body = String(e.doc);
		String desc = body.is_empty() ? sig : (sig + "\n\n" + body);

		d["result"]        = OK;
		d["type"]          = 4;   // LOOKUP_RESULT_CLASS_METHOD
		d["class_name"]    = ns;
		d["class_member"]  = mem;
		d["description"]   = desc;
		d["tooltip"]       = desc;
		d["doc"]           = desc;
		return d;
	}

	// Symbol not in our API table — not an error, just not ours. The
	// editor falls back to its built-in lookup (Lua keywords, locals).
	return d;
}
