#!/usr/bin/env python
"""Generate ApiData.gen.cpp from psxsplash-main/src/luaapi.hh.

Parses the structured `// Namespace.Method(args) -> retval` comment
blocks that sit above each static bind in luaapi.hh, accumulates
preceding `//` lines as docstrings, and emits a C++ source file with
a static array the editor autocomplete can walk.

Mirrors the same pattern as addons/ps1godot/tools/LuaApiStubGenerator.cs
so the in-editor completion surface matches the EmmyLua stubs shipped
to external editors. Re-run on every scons build.

Invocation:
    python gen_api_data.py <luaapi.hh path> <output .cpp path>
"""
import re
import sys
from pathlib import Path


SIG_LINE = re.compile(
    r"^\s*//\s*(?P<ns>[A-Z][A-Za-z0-9]+)\."
    r"(?P<name>[A-Za-z_][A-Za-z0-9_]*)"
    r"\s*\((?P<args>[^)]*)\)"
    r"(?:\s*->\s*(?P<ret>.+?))?\s*$"
)


def parse(lines):
    """Walk `lines` top-to-bottom, return a list of dicts:
        {ns, name, args, ret, doc}

    Convention in luaapi.hh: the structured signature comment comes
    FIRST, then any number of `//` description lines, then the
    `static int Foo_Bar(lua_State* L);` declaration. Example:

        // Entity.Find(name) -> object or nil
        // Finds first object with matching name (user-friendly)
        // (and any further description lines)
        static int Entity_Find(lua_State* L);

    So the parse loop tracks an "active entry" once a SIG_LINE is
    seen; subsequent `//` lines accumulate into that entry's doc
    until any non-`//` line (typically the static declaration)
    finalizes it. A new SIG_LINE before a non-comment line also
    finalizes the previous entry — handles "two adjacent
    signature comments with no docs" cleanly.
    """
    entries = []
    cur = None        # entry currently collecting docs
    doc_lines = []    # accumulator for cur

    def finalize():
        nonlocal cur, doc_lines
        if cur is None:
            return
        cur["doc"] = "\n".join(doc_lines).strip()
        entries.append(cur)
        cur = None
        doc_lines = []

    for line in lines:
        m = SIG_LINE.match(line)
        if m:
            # New signature — flush any prior entry first.
            finalize()
            cur = {
                "ns": m.group("ns"),
                "name": m.group("name"),
                "args": (m.group("args") or "").strip(),
                "ret": (m.group("ret") or "").strip(),
            }
            continue

        stripped = line.lstrip()
        if stripped.startswith("//") and cur is not None:
            body = stripped[2:].lstrip().rstrip()
            doc_lines.append(body)
        else:
            # Non-comment line (or `//` outside a sig context) —
            # close out the current entry. The static declaration
            # underneath the doc block is the typical trigger.
            finalize()

    # File may end mid-block (no trailing static decl).
    finalize()
    return entries


def cescape(s):
    """Escape a string for a C++ raw string literal.

    We use `R"api(...)api"` so we can drop quotes + backslashes without
    escaping. The one sequence that would close the literal is
    `)api"` — substitute that if it ever appears.
    """
    return s.replace(')api"', ')_api"')


def emit(entries, out_path):
    lines = [
        "// AUTO-GENERATED by gen_api_data.py from psxsplash-main/src/luaapi.hh.",
        "// Re-runs on every scons build. Do NOT edit by hand.",
        "",
        '#include "ApiData.gen.hpp"',
        "",
        "namespace ps1lua {",
        "",
        "const ApiEntry API_ENTRIES[] = {",
    ]
    for e in entries:
        lines.append("    {")
        lines.append(f'        /* ns       */ R"api({cescape(e["ns"])})api",')
        lines.append(f'        /* name     */ R"api({cescape(e["name"])})api",')
        lines.append(f'        /* args     */ R"api({cescape(e["args"])})api",')
        lines.append(f'        /* ret      */ R"api({cescape(e["ret"])})api",')
        lines.append(f'        /* doc      */ R"api({cescape(e["doc"])})api",')
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append(f"const int API_ENTRY_COUNT = {len(entries)};")
    lines.append("")
    lines.append("} // namespace ps1lua")
    lines.append("")
    Path(out_path).write_text("\n".join(lines), encoding="utf-8")


def main(argv):
    if len(argv) != 3:
        print("usage: gen_api_data.py <luaapi.hh> <ApiData.gen.cpp>",
              file=sys.stderr)
        return 2
    src = Path(argv[1])
    dst = Path(argv[2])
    if not src.exists():
        print(f"[gen_api_data] source not found: {src}", file=sys.stderr)
        return 1
    lines = src.read_text(encoding="utf-8", errors="replace").splitlines()
    entries = parse(lines)
    emit(entries, dst)
    print(f"[gen_api_data] {len(entries)} API entries -> {dst}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
