#!/usr/bin/env python
"""Generate ApiData.gen.cpp from psxsplash-main/src/luaapi.hh.

Parses the structured `// Namespace.Method(args) -> retval` comment
blocks that sit above each static bind in luaapi.hh, accumulates
preceding `//` lines as docstrings, and emits a C++ source file with
a static array the editor autocomplete can walk.

Mirrors the same pattern as addons/ps1godot/tools/LuaApiStubGenerator.cs
so the in-editor completion surface matches the EmmyLua stubs shipped
to external editors. Re-run on every scons build.

Invocation:
    python gen_api_data.py <luaapi.hh path> <output .cpp path>
"""
import re
import sys
from pathlib import Path


SIG_LINE = re.compile(
    r"^\s*//\s*(?P<ns>[A-Z][A-Za-z0-9]+)\."
    r"(?P<name>[A-Za-z_][A-Za-z0-9_]*)"
    r"\s*\((?P<args>[^)]*)\)"
    r"(?:\s*->\s*(?P<ret>.+?))?\s*$"
)


def parse(lines):
    """Walk `lines` top-to-bottom, return a list of dicts:
        {ns, name, args, ret, doc}
    `doc` is a `\n`-joined string of preceding `//` comment lines;
    a blank line resets the accumulator so unrelated earlier comments
    don't leak into the next bind.
    """
    entries = []
    doc_buf = []
    for line in lines:
        m = SIG_LINE.match(line)
        if m:
            entries.append({
                "ns": m.group("ns"),
                "name": m.group("name"),
                "args": (m.group("args") or "").strip(),
                "ret": (m.group("ret") or "").strip(),
                "doc": "\n".join(doc_buf).strip(),
            })
            doc_buf = []
            continue
        stripped = line.lstrip()
        if stripped.startswith("//"):
            body = stripped[2:].lstrip().rstrip()
            doc_buf.append(body)
        else:
            doc_buf = []
    return entries


def cescape(s):
    """Escape a string for a C++ raw string literal.

    We use `R"api(...)api"` so we can drop quotes + backslashes without
    escaping. The one sequence that would close the literal is
    `)api"` — substitute that if it ever appears.
    """
    return s.replace(')api"', ')_api"')


def emit(entries, out_path):
    lines = [
        "// AUTO-GENERATED by gen_api_data.py from psxsplash-main/src/luaapi.hh.",
        "// Re-runs on every scons build. Do NOT edit by hand.",
        "",
        '#include "ApiData.gen.hpp"',
        "",
        "namespace ps1lua {",
        "",
        "const ApiEntry API_ENTRIES[] = {",
    ]
    for e in entries:
        lines.append("    {")
        lines.append(f'        /* ns       */ R"api({cescape(e["ns"])})api",')
        lines.append(f'        /* name     */ R"api({cescape(e["name"])})api",')
        lines.append(f'        /* args     */ R"api({cescape(e["args"])})api",')
        lines.append(f'        /* ret      */ R"api({cescape(e["ret"])})api",')
        lines.append(f'        /* doc      */ R"api({cescape(e["doc"])})api",')
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append(f"const int API_ENTRY_COUNT = {len(entries)};")
    lines.append("")
    lines.append("} // namespace ps1lua")
    lines.append("")
    Path(out_path).write_text("\n".join(lines), encoding="utf-8")


def main(argv):
    if len(argv) != 3:
        print("usage: gen_api_data.py <luaapi.hh> <ApiData.gen.cpp>",
              file=sys.stderr)
        return 2
    src = Path(argv[1])
    dst = Path(argv[2])
    if not src.exists():
        print(f"[gen_api_data] source not found: {src}", file=sys.stderr)
        return 1
    lines = src.read_text(encoding="utf-8", errors="replace").splitlines()
    entries = parse(lines)
    emit(entries, dst)
    print(f"[gen_api_data] {len(entries)} API entries -> {dst}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
